#!/bin/sh
# configuration and template paths have changed

TEMPLATE=/tmp/usage.txt
[ -e $TEMPLATE ] && mv $TEMPLATE /etc/confconsole/

CONFFILE=/tmp/confconsole.conf
[ -e $CONFFILE ] && mv $CONFFILE /etc/confconsole/

#DEBHELPER#

exit 0
