#!/bin/sh
# configuration and template paths have changed

TEMPLATE=/usr/share/confconsole/templates/usage.txt
[ -e $TEMPLATE ] && cp $TEMPLATE /tmp/

CONFFILE=/etc/confconsole.conf
[ -e $CONFFILE ] && cp $CONFFILE /tmp/

#DEBHELPER#

exit 0
